import { useEffect, useState } from "react";
import { getProfile, registerPlayerPushSubscription, saveProfile, sendNotificationTest } from "./firebase.js";
const VAPID_PUBLIC_KEY = "BO3rO2tkbCVPTgCa-wRgEMBDbLnTpC9lupFIW594liQae2NUxfyxT9P_zjrKG_C_8FTQSRYMdhKITKVFoETPu9Q";
const topics = [["results", "Résultats et points"], ["predictionReminders", "Rappels avant clôture"], ["quizBonus", "Quiz et bonus"], ["announcements", "Annonces importantes"]];
const channels = [["email", "Email · bientôt", true], ["telegram", "Telegram", false], ["push", "Push navigateur", false]];
const emptyPreferences = Object.fromEntries(topics.map(([key]) => [key, Object.fromEntries(channels.map(([channel]) => [channel, false]))]));
function applicationServerKey(value) { const padding = "=".repeat((4 - value.length % 4) % 4); const raw = atob((value + padding).replace(/-/g, "+").replace(/_/g, "/")); return Uint8Array.from([...raw].map((character) => character.charCodeAt(0))); }
export default function NotificationsPanel() {
  const [profile, setProfile] = useState(null); const [telegramChatId, setTelegramChatId] = useState(""); const [preferences, setPreferences] = useState(emptyPreferences); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  useEffect(() => { getProfile().then(({ data }) => { setProfile(data); setTelegramChatId(data.telegramChatId ?? ""); setPreferences(data.notificationPreferences ?? emptyPreferences); }).catch((error) => setMessage(error.message)); }, []);
  function toggle(topic, channel) { if (channel === "email") return; setPreferences((current) => ({ ...current, [topic]: { ...current[topic], [channel]: !current[topic][channel] } })); }
  async function persist() { const enabledPreferences = Object.fromEntries(Object.entries(preferences).map(([topic, value]) => [topic, { ...value, email: false }])); await saveProfile({ displayName: profile.displayName ?? null, avatarInitiales: profile.avatarInitiales ?? null, equipeCoeurId: profile.equipeCoeurId ?? null, notifEmail: false, notifTelegram: Object.values(enabledPreferences).some((value) => value.telegram), notifPush: Object.values(enabledPreferences).some((value) => value.push), telegramChatId: telegramChatId.trim() || null, notificationPreferences: enabledPreferences }); setPreferences(enabledPreferences); }
  async function save() { setBusy("save"); setMessage(""); try { await persist(); setMessage("Préférences enregistrées."); } catch (error) { setMessage(error.message); } finally { setBusy(""); } }
  async function enablePush() { setBusy("push-connect"); setMessage(""); try { if (!("serviceWorker" in navigator) || !("PushManager" in window)) throw new Error("Ce navigateur ne prend pas en charge les notifications push."); const permission = await Notification.requestPermission(); if (permission !== "granted") throw new Error("Autorisation push refusée dans le navigateur."); const registration = await navigator.serviceWorker.ready; let subscription = await registration.pushManager.getSubscription(); if (!subscription) subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: applicationServerKey(VAPID_PUBLIC_KEY) }); await registerPlayerPushSubscription({ subscription: subscription.toJSON() }); setMessage("Ce navigateur est connecté aux notifications push."); } catch (error) { setMessage(error.message); } finally { setBusy(""); } }
  async function test(channel) { setBusy(channel); setMessage(""); try { await persist(); await sendNotificationTest({ channel }); setMessage(`Notification ${channel} envoyée.`); } catch (error) { setMessage(error.message); } finally { setBusy(""); } }
  if (!profile) return <p>{message || "Chargement des notifications…"}</p>;
  return <section className="notification-settings"><h2>🔔 Mes notifications</h2><p>Choisis précisément ce que tu reçois par Telegram ou sur ce navigateur. L’email applicatif sera activé plus tard.</p><div className="notification-matrix" role="group" aria-label="Préférences de notifications"><div className="matrix-heading" />{channels.map(([key, label]) => <strong className="matrix-heading" key={key}>{label}</strong>)}{topics.map(([topic, label]) => <div className="notification-row" key={topic}><span>{label}</span>{channels.map(([channel, channelLabel, disabled]) => <label className={disabled ? "channel-disabled" : ""} key={channel}><input type="checkbox" checked={disabled ? false : preferences[topic][channel]} disabled={disabled} onChange={() => toggle(topic, channel)} /><span className="sr-only">{label} par {channelLabel}</span></label>)}</div>)}</div><label>Identifiant Telegram<input inputMode="numeric" value={telegramChatId} onChange={(event) => setTelegramChatId(event.target.value.replace(/[^0-9-]/g, ""))} placeholder="Ex. 6888277125" /></label><div className="account-actions"><button type="button" onClick={enablePush} disabled={Boolean(busy)}>Connecter ce navigateur</button><button type="button" onClick={() => test("telegram")} disabled={Boolean(busy)}>Tester Telegram</button><button type="button" onClick={() => test("push")} disabled={Boolean(busy)}>Tester le push</button></div><button type="button" className="account-primary" onClick={save} disabled={Boolean(busy)}>{busy === "save" ? "Enregistrement…" : "Enregistrer"}</button>{message ? <p role="status">{message}</p> : null}</section>;
}
