import { useEffect, useState } from "react";
import { collection, getDocs } from "firebase/firestore";
import { db, getProfile, saveProfile } from "./firebase.js";

export default function Profile({ section = "identity", onSaved }) {
  const [profile, setProfile] = useState(null); const [clubs, setClubs] = useState([]);
  const [displayName, setDisplayName] = useState(""); const [avatarInitiales, setAvatarInitiales] = useState(""); const [equipeCoeurId, setEquipeCoeurId] = useState("");
  const [status, setStatus] = useState({ saving: false, error: "", saved: false });
  useEffect(() => { Promise.all([getProfile(), getDocs(collection(db, "clubs"))]).then(([response, snapshot]) => { const value = response.data; setProfile(value); setDisplayName(value.displayName ?? ""); setAvatarInitiales(value.avatarInitiales ?? ""); setEquipeCoeurId(value.equipeCoeurId == null ? "" : String(value.equipeCoeurId)); setClubs(snapshot.docs.map((doc) => ({ id: doc.id, nom: doc.data().nom ?? doc.id })).sort((a, b) => a.nom.localeCompare(b.nom))); }).catch((error) => setStatus((current) => ({ ...current, error: error.message }))); }, []);
  async function submit(event) { event.preventDefault(); setStatus({ saving: true, error: "", saved: false }); try { await saveProfile({ displayName: displayName.trim() || null, avatarInitiales: avatarInitiales.trim() || null, equipeCoeurId: equipeCoeurId === "" ? null : Number(equipeCoeurId), notifEmail: profile.notifEmail ?? true, notifPush: profile.notifPush ?? false, notifTelegram: profile.notifTelegram ?? false, telegramChatId: profile.telegramChatId ?? null, notificationPreferences: profile.notificationPreferences }); setStatus({ saving: false, error: "", saved: true }); onSaved?.(); } catch (error) { setStatus({ saving: false, error: error.message, saved: false }); } }
  if (!profile) return <p>{status.error ? `Erreur profil : ${status.error}` : "Chargement du profil…"}</p>;
  return <form onSubmit={submit} className="account-form">{section === "identity" ? <><h2>✏️ Mon identité</h2><label>Pseudo<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} maxLength="40" /></label><label>Initiales de l’avatar <small>1 ou 2 caractères, laisse vide pour les générer depuis ton pseudo.</small><input className="initials-input" value={avatarInitiales} onChange={(event) => setAvatarInitiales(event.target.value)} maxLength="2" /></label></> : <><h2>⭐ Mon équipe de cœur</h2><label>Choisir un club (facultatif)<select value={equipeCoeurId} onChange={(event) => setEquipeCoeurId(event.target.value)}><option value="">Aucune</option>{clubs.map((club) => <option key={club.id} value={club.id}>{club.nom}</option>)}</select></label></>}<button className="account-primary" disabled={status.saving}>{status.saving ? "Enregistrement…" : "Enregistrer"}</button>{status.saved ? <p className="success">Modification enregistrée.</p> : null}{status.error ? <p className="error">{status.error}</p> : null}</form>;
}
